- name: cloudalchemy.node-exporter
- name: cloudalchemy.snmp-exporter
- name: cloudalchemy.blackbox-exporter
- name: cloudalchemy.prometheus
- name: cloudalchemy.alertmanager
- name: cloudalchemy.grafana

# EXTRAS
- name: SoInteractive.docker
  version: 0.11.6
- name: antoiner77.caddy
  version: v2.0.4
