---
collections:
# With just the collection name
- name: community.general
  type: galaxy
- name: prometheus.prometheus
  type: galaxy
- name: devsec.hardening
  type: galaxy
- name: grafana.grafana
  type: galaxy
  version: ">=5.2.0"

roles:
# EXTRAS
- name: caddy_ansible.caddy_ansible
- name: hifis.unattended_upgrades
  version: "v3.2.1"
