---
collections:
# With just the collection name
- name: prometheus.prometheus
  type: galaxy
- name: devsec.hardening
  type: galaxy

roles:
- name: cloudalchemy.grafana

# EXTRAS
- name: caddy_ansible.caddy_ansible
- name: jnv.unattended-upgrades
  version: v1.7.1
