---
collections:
# With just the collection name
- name: community.general
  type: galaxy
  version: 10.4.0
- name: prometheus.prometheus
  type: galaxy
  version: 0.25.0
- name: devsec.hardening
  type: galaxy
  version: 10.3.0
- name: grafana.grafana
  type: galaxy
  version: 5.6.0

roles:
# EXTRAS
- name: caddy_ansible.caddy_ansible
  version: "v3.2.0"
- name: hifis.unattended_upgrades
  version: "v3.2.1"
