---
collections:
# With just the collection name
- name: community.general
  type: galaxy
  version: 11.3.0
- name: prometheus.prometheus
  type: galaxy
  version: 0.27.3
- name: devsec.hardening
  type: galaxy
  version: 10.3.1
- name: grafana.grafana
  type: galaxy
  version: 6.0.3
- name: hifis.toolkit
  type: galaxy
  version: 6.1.0

roles:
# EXTRAS
- name: caddy_ansible.caddy_ansible
  version: "v3.2.0"
